set(CPACK_GENERATOR "TGZ;ZIP" CACHE STRING "Semicolon separated list of generators")

set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 0)
set(CPACK_INSTALL_CMAKE_PROJECTS "${CMAKE_BINARY_DIR}" "${PROJECT_NAME}" ALL .)

set(CPACK_PACKAGE_NAME "occ-imgui")
set(CPACK_PROJECT_URL "https://github.com/paulbuechner/occ-imgui")
set(CPACK_PACKAGE_VENDOR "Paul Büchner")
set(CPACK_PACKAGE_CONTACT "Paul Büchner <paul-buechner_86432180@outlook.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "An example project integrating OpenCASCADE with ImGui for 3D visualization and GUI rendering.")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
if(PROJECT_VERSION_TWEAK)
    set(CPACK_PACKAGE_VERSION ${CPACK_PACKAGE_VERSION}.${PROJECT_VERSION_TWEAK})
endif()
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_SOURCE_DIR}/packages")

# Optionally add NSIS if it's available
if(NSIS_MAKENSIS_EXECUTABLE)
    message(STATUS "Using NSIS_MAKENSIS_EXECUTABLE: ${NSIS_MAKENSIS_EXECUTABLE}")
    set(NSIS_MAKENSIS_EXECUTABLE ${NSIS_MAKENSIS_EXECUTABLE} CACHE FILEPATH
        "Path to makensis.exe")
else()
    find_program(NSIS_MAKENSIS_EXECUTABLE makensis)
endif()

if(NSIS_MAKENSIS_EXECUTABLE)
    list(APPEND CPACK_GENERATOR "NSIS")
    set(CPACK_NSIS_MODIFY_PATH ON) # Does not work always
endif()

include(CPack)
